### ISSUE TITLE
SP public and private key

### ISSUE THREAD

**Issue by pitbulk** [MindPointGroup/django-saml2-pro-auth#1]
The python-saml plugin already is able to read public and private key from file so the setting:
```
"x509cert": open(os.path.join(BASE_DIR,'certs/sp.crt'), 'r').read(),
 "privateKey": open(os.path.join(BASE_DIR,'certs/sp.key'), 'r').read(),
 ```

Is not really required

**Comment by defionscode** [comment]
hmm based on your docs I thought the only options were for `certs/sp.crt` and `certs/sp.key`. if a user wants to use a different path are they able to supply a path as the value? If no, then I'll update the docs to make that difference clear. In other words, do `open` only when your certs/keys are in a diff path.

**Comment by pitbulk** [comment]
Yes, use the custom_base_path parameter to define a custom path for your certs.
https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/settings.py#L95

**Comment by defionscode** [comment]
ah, totally missed it. taking a look at your source, seems like using `open()` would still be alright with the idp cert since it seems that `python3-saml` doesn't have a default file it looks for. Which is fine anyway i think.

**Comment by pitbulk** [comment]
Yes for IdP cert toolkit doesnt read from a file and need to be provided by setting value.

Ideally makes sense to create a saml setting model and a django admin interface and let admin to provide all saml data using a form ... On a multi-tenant solution, be able to store a SAML setting per tenant.

**Comment by defionscode** [comment]
agreed that would be a nice feature

**Comment by defionscode** [comment]
That is something we will probably add in at some point it just wont be very soon based on our current internal needs. Though, I would def take in a PR for it.

**Comment by defionscode** [comment]
updated readme
