### ISSUE TITLE
bug SAML_ROUTE is not really optional

### ISSUE THREAD

**Issue by rezende** [MindPointGroup/django-saml2-pro-auth#14]
Despite what the documentation says, not setting SAML_ROUTE throws an error on:

https://github.com/MindPointGroup/django-saml2-pro-auth/blob/8e1842c9e050d9c7fde07d41eb7f650e1e61f578/src/django_saml2_pro_auth/urls.py#L8

**Comment by defionscode** [comment]
what's the error? NameError undefined?

**Comment by rezende** [comment]
AttributeError: 'settings' object has no attribute 'SAML_ROUTE'

**Comment by defionscode** [comment]
Fixed by e52cfda7c539ff94765361bf2f5a97322bee996c

**Comment by rezende** [comment]
Thanks! To be honest, I tried to fix this but I wanted to write tests that assert it was working. That was where I got stuck
