### ISSUE TITLE
Should the first provider be used as the default?

### ISSUE THREAD

**Issue by EricHigdon** [MindPointGroup/django-saml2-pro-auth#19]
It seems a bit excessive to have to define which provider to use on every login attempt. Perhaps if 'provider' is not present in the GET data, it should fallback to the first provider in the settings. Any concerns with something like pull request #21?

**Comment by defionscode** [comment]
I'm ok adding this behavior

**Comment by defionscode** [comment]
Only concern with the PR is it's causing tests to fail. Otherwise I think this is an acceptable behavior
