### ISSUE TITLE
KeyError at /sso/saml/

### ISSUE THREAD

**Issue by santiagovassallo** [MindPointGroup/django-saml2-pro-auth#23]
Hello! I'm having an issue with the user mapping process, because the configuration of the saml where I work doesn't return the key if the user doesn't have the atribute. So when it reaches to the point of mapping, it's possible that saml_data doesn't have one or more keys that have been specified in the SAML_USERS_MAP.

Is it possible to consider this and maybe do this process less strict by controlling if the user_key is in saml_data before asigning it?

Thank you a lot!

**Comment by defionscode** [comment]
Moving discussion to your PR

**Comment by defionscode** [comment]
Addressed in #24, available on PyPi under version `0.0.7` and in the source under a git tag with the same version. Thank you for your contribution @santiagovassallo!

**Comment by santiagovassallo** [comment]
You are welcome! And thank you for this awesome project!
