### ISSUE TITLE
prepare_django_request should use request.get_host()

### ISSUE THREAD

**Issue by tecknicaltom** [MindPointGroup/django-saml2-pro-auth#30]
Instead of using `request.META['HTTP_HOST']`, `prepare_django_request` should use `request.get_host()` so that it works properly for app servers behind a proxy. In this configuration, Django should be configured with `USE_X_FORWARDED_HOST` so that `request.get_host()` uses the value from the `X-FORWARDED-HOST` header instead of `Host`.

**Comment by defionscode** [comment]
I'm up for a pull request!

**Comment by defionscode** [comment]
addressed in version `0.0.10`
