### ISSUE TITLE
How does SAML_REDIRECT work ?

### ISSUE THREAD

**Issue by rezende** [MindPointGroup/django-saml2-pro-auth#9]
Hi,

From what I understand of the flow, the IDP is looking at my metadata endpoint and calling http://mydomain.com/sso/saml/?acs&provider=myprovider to authenticate the user.

What I want to do is redirect the user after authentication to a specific page.

I thought SAML_REDIRECT would do this but it looks like it does not work that way.

SAML_REDIRECT  is only used if `acs` is not on the URL, since it's a `elif` instead of a `if`.

https://github.com/voxy/django-saml2-pro-auth/blob/master/src/django_saml2_pro_auth/views.py#L50

Can I have an example on how to use this setting?

Thanks a lot!

**Comment by defionscode** [comment]
You're using it properly, I think I simply missed at key for a kwarg on the `auth.login()` call. See this for info: https://github.com/onelogin/python3-saml/blob/07bb2ba245d3aebbd24c808a1823b12645f4d755/src/onelogin/saml2/auth.py#L321

I've made a pull request. Would you be able to test it out? https://github.com/MindPointGroup/django-saml2-pro-auth/pull/11

**Comment by rezende** [comment]
I've added a comment there

**Comment by defionscode** [comment]
seems like this is fixed, a new version has been cut and uploaded to pypi
